### ISSUE TITLE
Failed to create detour setup handle

### ISSUE THREAD

**Issue by Joaquel** [Mikusch/PropHunt#10]
When gamemode loads (Windows, using last Sourcemod Stable Version), this appears:

```
Failed to create detour setup handle for CTFPlayer::GetMaxHealthForBuffing
Failed to create detour setup handle for CTeamplayRoundBasedRules::SetInWaitingForPlayers
```

**Comment by Mikusch** [comment]
Works fine for my Windows machine, perhaps you have other plugins using the same gamedata? Also make sure gamedata is updated,

**Comment by Joaquel** [comment]
Gamedata is updated.
And i have more gamemodes using same gamedata i think.

**Comment by Mikusch** [comment]
> And i have more gamemodes using same gamedata i think.

If they're loaded at the same time, this will cause issues. Detouring a function changes its signature, which will cause subsequent detours not to function.

**Comment by Joaquel** [comment]
> If they're loaded at the same time, this will cause issues. Detouring a function changes its signature, which will cause subsequent detours not to function.

Ohh, makes sense.
All gamemodes loads but they get unloaded within the server.cfg and load a specific gamemode with MapConfigs.
