### ISSUE TITLE
Failed to create detour setup handle & failed to create SDKCall

### ISSUE THREAD

**Issue by Synopt** [Mikusch/PropHunt#33]
Hey there, thanks very much for making this plugin! 

I've tried running it on a server and I'm getting:
```
L 09/13/2024 - 21:00:25: [prophunt.smx] Failed to create detour setup handle for CTFPlayer::GetMaxHealthForBuffing
L 09/13/2024 - 21:00:25: [prophunt.smx] Failed to create detour setup handle for CTFProjectile_GrapplingHook::HookTarget
L 09/13/2024 - 21:00:25: [prophunt.smx] Failed to create detour setup handle for CTFPlayerShared::Heal
L 09/13/2024 - 21:00:25: [prophunt.smx] Failed to create detour setup handle for CTFPistol_ScoutPrimary::Push
L 09/13/2024 - 21:00:25: [prophunt.smx] Failed to create SDKCall: AI_CriteriaSet::FindCriterionIndex
```

I'm sure I'm doing something wrong but I can't figure it out... I've looked at this issue https://github.com/Mikusch/PropHunt/issues/10 but I didn't quite understand the resolution, also I appear to have other failures., like the `Failed to create SDKCall`

I don't think I've got any other plugins trying to create duplicate detours but I'm not sure about the multiple gamemodes mentioned in that issue.

My list of plugins in `sourcemod/plugins` is
```
tf2utils.smx
admin-flatfile.smx
adminhelp.smx
adminmenu.smx
antiflood.smx
basebans.smx
basechat.smx
basecomm.smx
basecommands.smx
basetriggers.smx
basevotes.smx
clientprefs.smx
funcommands.smx
funvotes.smx
nextmap.smx
playercommands.smx
prophunt.smx
reservedslots.smx
sounds.smx
tf_econ_data.smx
tf2attributes.smx
```

Thanks in advance!

**Comment by Mikusch** [comment]
Looks to me like you downloaded the GitHub release package, which is very, very outdated and long defunct due to game updates. I've set up automated releases, so you should be able to grab the latest one now.

**Comment by Synopt** [comment]
It works like a dream! Thank you so much again for making and supporting this awesome plugin 🎉
